version: "3.7"

services:
  frontend:
    build: frontend
    environment:
      - BACKEND_SERVER=backend
      - DEBUG=False
    ports:
      - 8502:8502
    depends_on:
      - backend
    volumes:
      - ./frontend:/workspace
      - ./data:/data
    restart: always

  backend:
    build: backend
    ports:
      - 45678:45678
    volumes:
      - ./backend:/workspace
      - ./data:/data
    restart: always
